### ISSUE TITLE
is tls_client really needed?

### ISSUE THREAD

**Issue by ItsCEED** [cullenwatson/JobSpy#37]
Just wondering, as its slow, buggy and cant be async, and the support for it unknown.

**Comment by cullenwatson** [comment]
Yes, to bypass cloud flare for indeed and zip recruiter. If you know another way that's faster, we'll switch

**Comment by cullenwatson** [comment]
Should be less buggy now, added time out on the requests

**Comment by ItsCEED** [comment]
ah i see, i wasnt sure what indeed uses..
Sadly, we don't have anything better for python, and the tls_client Is well unmaintained, not even a maintained fork..

**Comment by fred2026** [comment]
Sadly, the tls_client didn't bypass the cloud flare with zip recruiter on my Oracle server, is there any thing I could try without using a proxy?

**Comment by ItsCEED** [comment]
@ZacharyHampton you will be blessed by many.

@fred2026 your IP got ripped right there..

**Comment by cullenwatson** [comment]
> Sadly, the tls_client didn't bypass the cloud flare with zip recruiter on my Oracle server, is there any thing I could try without using a proxy?

I'll work on adding proxies now.

**Comment by fred2026** [comment]
> I'll work on adding proxies now.

Thank you very much!

**Comment by cullenwatson** [comment]
> Sadly, the tls_client didn't bypass the cloud flare with zip recruiter on my Oracle server, is there any thing I could try without using a proxy?

@fred2026 It's due to [Python-Tls-Client](https://github.com/FlorianREGAZ/Python-Tls-Client) having not updated their dependencies in 5 months off of [tls-client](https://github.com/bogdanfinn/tls-client). If I create a fork and update the binaries, should work. Will try in a bit

**Comment by fred2026** [comment]
> 

Looking forward to your updates. The new tls-client sure will help a lot!

**Comment by cullenwatson** [comment]
> Sadly, the tls_client didn't bypass the cloud flare with zip recruiter on my Oracle server, is there any thing I could try without using a proxy?

@fred2026 which oracle server are you running?

**Comment by fred2026** [comment]
> 

I have an Oracle server under its free tire and another AWS light sail server. The Indeed scraper runs great, but LinkedIn and zip recruiter seem can't pass the Cloudflare CAPTCHA.

**Comment by cullenwatson** [comment]
Did you try proxies?

**Comment by fred2026** [comment]
> Did you try proxies?

Yes, I finally got a better proxy and the problems are gone! Thank you!

**Comment by Ahmed-M-Osman** [comment]
@fred2026 
Can you please share how to get proxies to use for LinkedIn?
I have no clue what to add to avoid getting blocked, I now only scrape 100 jobs per day since I'm too scared to get my IP blocked
