### ISSUE TITLE
Class type error

### ISSUE THREAD

**Issue by ahnafaf** [cullenwatson/JobSpy#41]
Can somebody else please check the class input for `site_name` parameter in `scrape_jobs()`?

`
Argument of type "list[str]" cannot be assigned to parameter "site_name" of type "str | Site | List[Site]" in function "scrape_jobs"
  "Literal['linkedin']" is incompatible with "Site"
  "Literal['zip_recruiter']" is incompatible with "Site"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
`

This is the error I keep receiving.

**Comment by cullenwatson** [comment]
@ahnafaf what python version are you using and can you paste your `scrape_jobs()` code

**Comment by ZacharyHampton** [comment]
@ahnafaf Upgrade and try it out now
