### ISSUE TITLE
ZipRecruiter - HTML variant

### ISSUE THREAD

**Issue by cullenwatson** [cullenwatson/JobSpy#45]
There's a rare bug where they send you a different html page that isn't supported by the bot. Have not received the page enough due to probability to debug it properly

**Comment by cullenwatson** [comment]
works for me, are you setting this value to None?

![image](https://github.com/cullenwatson/JobSpy/assets/78247585/459ab5a7-9b25-4b2a-93e2-667ff72a6f3f)

**Comment by fred2026** [comment]
> works for me, are you setting this value to None?
> 
> ![image](https://user-images.githubusercontent.com/78247585/266693357-459ab5a7-9b25-4b2a-93e2-667ff72a6f3f.png)

![2023-09-09_06-04](https://github.com/cullenwatson/JobSpy/assets/136940801/89473dbf-2639-415b-a625-7a759c57cbf0)
Like this, the description is truncated.

**Comment by cullenwatson** [comment]
If it can't fetch the full description, it uses a truncated version. Try a few queries; they shouldn't all be shortened

**Comment by fred2026** [comment]
Sorry for my late reply, I got the full description after switching to a better proxy. `process_job_javascript ` works great. Thank you for your great work.
