### ISSUE TITLE
Extracting emails from job postings

### ISSUE THREAD

**Issue by esxr** [cullenwatson/JobSpy#47]
Is there a way to extract emails and other contact data from the job posting (if it exists). That could prove invaluable.

**Comment by cullenwatson** [comment]
I've never really seen job postings with emails in it. Can you provide some examples so I know it's worth it?

**Comment by esxr** [comment]
The emails (if any) are usually in the job description. Personally, I've seen that at least around 1/7th of the job descriptions have emails. That being said, I have found a way to extract the emails. Let me know if you want me to open a PR on the same :)

**Comment by cullenwatson** [comment]
Yes, please open a PR @esxr

**Comment by mellahysf** [comment]
@esxr could you share your version regarding email extraction? thanks

**Comment by cullenwatson** [comment]
@mellahysf the code extracts the emails already from description

**Comment by mellahysf** [comment]
thanks @cullenwatson 

Could you add extraction of sector and category please?

**Comment by esxr** [comment]
Wow I see this discussion has picked up again. I had a business called ApplyAble (created in June 2023), which allowed people to extract job postings from Linkedin, Seek, Indeed etc., and send tailored applications to recruiters and companies. 

I guess the idea was very premature (and also a bit hackish) and I didn't have the required resources to execute it back then. 

I have the entire codebase established for that. @mellahysf please contact me if you plan to proceed at pranav@dhoolia.com. I have since then refined the idea to be a two-sided marketplace for matching applicants and companies based on AI.
