### ISSUE TITLE
macOS Catalina - unsupported

### ISSUE THREAD

**Issue by sasa-buklijas** [cullenwatson/JobSpy#48]
On OSX 10.15, python 3.11.5

>>> import jobspy
Segmentation fault: 11

>>> from jobspy import scrape_jobs
Segmentation fault: 11

Any ideas ?

**Comment by ZacharyHampton** [comment]
Most likely due to the tls_client binary not supporting your architecture.

**Comment by ZacharyHampton** [comment]
> Most likely due to the tls_client binary not supporting your architecture.

https://github.com/bogdanfinn/tls-client/issues/16

**Comment by sasa-buklijas** [comment]
Can be mentioned in REDME ?

**Comment by cullenwatson** [comment]
I'll just leave it open for future reference

**Comment by sasa-buklijas** [comment]
IMHO better in README, in section as "not supported OS"
